// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: hello.proto

package helloPb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloerClient is the client API for Helloer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloerClient interface {
	SayHi(ctx context.Context, in *HiReq, opts ...grpc.CallOption) (*HiRsp, error)
}

type helloerClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloerClient(cc grpc.ClientConnInterface) HelloerClient {
	return &helloerClient{cc}
}

func (c *helloerClient) SayHi(ctx context.Context, in *HiReq, opts ...grpc.CallOption) (*HiRsp, error) {
	out := new(HiRsp)
	err := c.cc.Invoke(ctx, "/hello.Helloer/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloerServer is the server API for Helloer service.
// All implementations must embed UnimplementedHelloerServer
// for forward compatibility
type HelloerServer interface {
	SayHi(context.Context, *HiReq) (*HiRsp, error)
	mustEmbedUnimplementedHelloerServer()
}

// UnimplementedHelloerServer must be embedded to have forward compatible implementations.
type UnimplementedHelloerServer struct {
}

func (UnimplementedHelloerServer) SayHi(context.Context, *HiReq) (*HiRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedHelloerServer) mustEmbedUnimplementedHelloerServer() {}

// UnsafeHelloerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloerServer will
// result in compilation errors.
type UnsafeHelloerServer interface {
	mustEmbedUnimplementedHelloerServer()
}

func RegisterHelloerServer(s grpc.ServiceRegistrar, srv HelloerServer) {
	s.RegisterService(&Helloer_ServiceDesc, srv)
}

func _Helloer_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloerServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Helloer/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloerServer).SayHi(ctx, req.(*HiReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Helloer_ServiceDesc is the grpc.ServiceDesc for Helloer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helloer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Helloer",
	HandlerType: (*HelloerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Helloer_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
